### ISSUE TITLE
`CUDA error: CUBLAS_STATUS_NOT_SUPPORTED` on Kubuntu 23.04 x86_64 with NVIDIA GeForce RTX 3090 Ti

### ISSUE THREAD

**Issue by PetervanLunteren** [agentmorris/MegaDetector#106]
@agentmorris An EcoAssist user has found a `CUDA error` while running inference on GPU. See https://github.com/PetervanLunteren/EcoAssist/issues/16 for more information.

I don't think it is an EcoAssist error, since the traceback originates from `run_detector_batch.py`. It [seems](https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544/4) that it can be caused if there is a mismatch between the dimension of the input tensor and the dimensions of the `nn.Linear` module. Any idea what is going on?

The environment is created with the `YAML` file below.
```
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  # We pin Pillow to make it as likely as possible that images are loaded via a loader that's identical to the training environment
  - Pillow=9.1.0 
  - tqdm
  - jsonpickle
  - humanfriendly
  - numpy
  - matplotlib
  - opencv
  - requests

  # So we can run Jupyter notebook this environment
  - nb_conda_kernels
  - ipykernel
  
  # For running MegaDetector v5
  - pandas
  - seaborn>=0.11.0
  - PyYAML>=5.3.1
  - pytorch::pytorch=1.10.1
  - pytorch::torchvision=0.11.2
  - conda-forge::cudatoolkit=11.3
  - conda-forge::cudnn=8.1

  # For running MegaDetector v4
  # - tensorflow>=2.0  
```

**Comment by agentmorris** [comment]
Thanks for the heads-up.  I'm going to close this issue and respond to the issue on the EcoAssist repo.

**Comment by agentmorris** [comment]
For posterity: this was resolved by running:

export LD_LIBRARY_PATH=''

...prior to starting EcoAssist.
